### ISSUE TITLE
WER and CER values that  in the last  exp.

### ISSUE THREAD

**Issue by smalissa** [tarekeldeeb/DeepSpeech-Quran#11]
@tarekeldeeb 
Assalam Alaikum 

can you provide me with the WER and CER values that you get them in the last version of your models in both ( output_graph.pb ) and ( output_graph_imams_tusers.pb ) and also what is the specification of the server that used?

**Comment by tarekeldeeb** [comment]
WER for the imam is about 0.05, and that for imam+users (from tarteel dataset) is about 0.1

Check this:
https://github.com/tarekeldeeb/DeepSpeech-Quran/issues/6

**Comment by smalissa** [comment]
ok how about the spec. of the recourses that used it for this results?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by tarekeldeeb** [comment]
There's a bash script in the bin folder that runs the training.  You don't have to tune the parameters.  Hw spec is not relevant,  you'll need a gpu with 8 GB of dedicated ram.  If you have less,  then you'll have to reduce the batch size, but will get the same results anyway.

**Comment by smalissa** [comment]
ok
script in the bin folder to see the parameters values that you used , isn’t it?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
