### ISSUE TITLE
optimaizatiom the WER result by more fine-tunning

### ISSUE THREAD

**Issue by smalissa** [tarekeldeeb/DeepSpeech-Quran#12]
assalam alikum
@tarekeldeeb , @aibrahim- 
i need some help to make the thing more clear for me
I have my own quranic data for female, it small (5665 records)
i get (0.608 ) WER value with n-hidden = 2048
I want to obtain more enhancement of WER, so I try to change alpha, the beta value only
I came to cross your work here and use your values as it used; I get (0.502) WER
i need to know why you used n-hidden= 1024 and not used the default values( 2048)?
what is the reason?
some of clarification.
thanks.

**Comment by smalissa** [comment]
@omerasif-itu
if you can help pleaze?

**Comment by tarekeldeeb** [comment]
Your WER are too little, how many iterations do you train?
From what I see, 1024 gives almost the same result and will consume less memory and CPU. This smaller network will be able to work with many android phones in real time.
This is the main reason I chose 1024 only.

I hope it's clear now.
