### ISSUE TITLE
Can give a clear and detailed script tutorial for training? 

### ISSUE THREAD

**Issue by ghost** [tarekeldeeb/DeepSpeech-Quran#13]
Thanks you

**Comment by tarekeldeeb** [comment]
Please re-check the home page again:
https://github.com/tarekeldeeb/DeepSpeech-Quran

**Comment by Sadmansamee** [comment]
@tarekeldeeb from the Home page I couldn't actually get many ideas about workflow. would appreciate more detail documents.
