### ISSUE TITLE
Tarteel data 

### ISSUE THREAD

**Issue by smalissa** [tarekeldeeb/DeepSpeech-Quran#14]
@tarekeldeeb 
@aibrahim- 
@omerasif-itu 
assalam aliakom
i want to ask about Tarteel data, I spent one week in  trying to download the Tarteel records and got it, but my internet connection is bad  ( area coverage problem ) so I can't complete the downloading process.
so if you can please send me or upload it in  some place the all Users dataset or the Filtered Users dataset (in one folder or maybe splitter it into number of folders ), i will thank you.

**Comment by tarekeldeeb** [comment]
@suhad-alissa I cannot understand your point. If you have an internet issue, what's the point of uploading another copy of the data?

The issues page is used to report code issues, behavioral issues .. etc.

**Comment by smalissa** [comment]
@tarekeldeeb 
thanks for your reply
i understand the issue page's policy and my ask is related as well.
my asking is: could you please upload the Tareel data version before it filtered witch’s called “Tusers” here on the GitHub?
with all thanks for you.

**Comment by tarekeldeeb** [comment]
The data size is too large, even after filtering. It's not suitable to be uploaded on git.

Can you use a USB flash disk to clone and run the download script,  from another place where the internet is stable? Then you can continue from the low internet area.

**Comment by smalissa** [comment]
@tarekeldeeb 
Thank you for your reply
Alhamd lilah, i could solve my problem and I was able to download all the records even before they filtered, where in my area at the middle of the night and until the early morning hours, the Internet connection is very good so i managed the issue this morning from 12 am to 10 am.
thank you
