### ISSUE TITLE
Share trained .tflite file and .scorer file

### ISSUE THREAD

**Issue by Sadmansamee** [tarekeldeeb/DeepSpeech-Quran#15]
Can anyone share their trained .tflite file and .scorer file? it would be really helpful

**Comment by Ahmad0Tanveer** [comment]
hello please share tflite and scoroer file with me 
**ahmad00tanveer@gmail.com**

**Comment by tarekeldeeb** [comment]
data/quran/output_graph_imams_tusers_v2.tflite

**Comment by Ahmad0Tanveer** [comment]
Okay Sir Thank you sooo much .

**Comment by Ahmad0Tanveer** [comment]
One more thing sir labels. can use quran verses for labels

**Comment by tarekeldeeb** [comment]
Yes, this is the idea.
Quran text is used as labels, speech is hte input.
--
Tarek Eldeeb | طارق الديب <https://www.linkedin.com/in/tarekeldeeb>
Sr. SW R&D Manager | FPGA Expert
