### ISSUE TITLE
Accuracy on the model provided

### ISSUE THREAD

**Issue by Sadmansamee** [tarekeldeeb/DeepSpeech-Quran#16]
I have made a [sample](https://github.com/GreentechApps/QuranTextFromVoiceDetector) demo Android project with the provided [model](https://github.com/tarekeldeeb/DeepSpeech-Quran/blob/master/data/quran/output_graph_imams_tusers_v2.tflite) with this repository, I can't really get enough accuracy, how do I improve it?

**Comment by tarekeldeeb** [comment]
This is an issue with Android. Converting the graph to a tflite somehow destroys the accuracy. 
This is a known issue. I'm still searching for a solution.
