### ISSUE TITLE
Tarteel data's gender in deepspeech model

### ISSUE THREAD

**Issue by smalissa** [tarekeldeeb/DeepSpeech-Quran#18]
@tarekeldeeb
@aibrahim-
@omerasif-itu
assalam aliakom
pleaze any one help me in the clarification because i have some  confusion at some points, if this possible and don’t mind.
I want to ask about the following  points on Tarteel data:

1.  In Imam model you traind and tested the model on professional resiter dataset , this means that the train data and dev and test have professional records, is this right ?

2. in Tarteel  data ,after you filter them, the dataset that’s used in  ( 18420 records), does them include males and females records , or only males records  ?.

3. in Imam + filtered users dataset that’s used: 
 what’s the data used in training set( Tusers only or Imam data only , or mix of Tusers and Imam data  ), and in dev set , and also in testing set ?
 in this step Is this  Tusers dataset contains female records or only  male records ?.

Thank you in advance.

**Comment by tarekeldeeb** [comment]
1- your understanding is correct
2- female voices are included
3- dataset is a mix (imam + filtered tarteel users)

Is the methodology clear enough for you?

**Comment by smalissa** [comment]
@tarekeldeeb
@aibrahim-
@omerasif-itu
thank you for reply and your clarification, but i still have some questions.


  1.    How many female records included in the (18,420 ) records were used? I tried to know this but i couldn't.
  2. 
  2.  In “ Imam + Tarteel users “ model, the data of records that’s used is like this:  
          - Train CSV file : mix of imam and Tuser records                                                         
          - Dev CSV file :  mix of imam and Tuser records                                                          
           - Test CSV file : mix of imam and Tuser records.                                                          
  Is this true ?

3. Also i need the final CSV files “train, dev, test “ that you used in “Imam + Tuser”  model. Can you upload it here or send it to me by email please?

with alot of thanks.

—————————————-
Suhad Al-Issa.
Computer Engineering.
Jordan,Irbid.
________________________________
