### ISSUE TITLE
Usage of pre-trained model - pbmm file missing

### ISSUE THREAD

**Issue by jasmindevgirl** [tarekeldeeb/DeepSpeech-Quran#21]
I found the models in data/quran.. They were named *.pb instead of the one I searched for *.pbmm. 

The web example works now with the *.pb file which is awesome! 

I get a warning tho (Warning: reading entire model file into memory. Transform model file into an mmapped graph to reduce heap usage.). 

There is a zip file which claims to have this .pbmm file but after extracting it there's no such file there and the extracted file does not work.. any idea?

Thanks for this awesome project!!

**Comment by tarekeldeeb** [comment]
Please use the converter:
https://github.com/tarekeldeeb/DeepSpeech-Quran/blob/master/data/quran/convert_graphdef_memmapped_format.zip

On a linux machine, just unzip it and run it on any *.pb to get a memory mapped *.pbmm
