### ISSUE TITLE
Workflow is not clear

### ISSUE THREAD

**Issue by tarekeldeeb** [tarekeldeeb/DeepSpeech-Quran#4]
Add a doc or flow chart like this:
![deepspeech-quran-flow](https://user-images.githubusercontent.com/90985/83131080-98cdd980-a0df-11ea-8801-dd325739fd15.png)

**Comment by smalissa** [comment]
Assalam Alaikum @tarekeldeeb 
 I have a question here:
 what are the meaning and the role of " filter user recordings "stage
can you explain to me in clear, please?
