### ISSUE TITLE
best model training checkpoints for fine-tuning

### ISSUE THREAD

**Issue by omerasif-itu** [tarekeldeeb/DeepSpeech-Quran#6]
Hi @tarekeldeeb,
Can you please provide best-dev checkpoints for [fine-tuning the model](https://deepspeech.readthedocs.io/en/v0.7.1/TRAINING.html#fine-tuning-same-alphabet)?

**Comment by tarekeldeeb** [comment]
Still working on that .. did not reach good number yet.

**Comment by omerasif-itu** [comment]
Right. I have tested few test samples and got a few good result. I was experimenting with common voice Arabic data and also experimenting transfer learning approach to modeling. I wonder If I could use your current best checkpoint for experimenting further; like there is checkpoint availble [here](https://github.com/mozilla/DeepSpeech/releases/tag/v0.7.1)

**Comment by rachidio** [comment]
Salam everyone,
@omerasif-itu what hardware config did you use to get those good results (and how much time did it take)?
Thanks

**Comment by omerasif-itu** [comment]
@rachidio I am such a naive. I tested training sample by mistake so that's why results were fine. now I just tested first surah with unknown reciter (Aziz Alili - audio files from everyayah.com ) and results are fine with two word errors. 
**Setup:** I tried google colab with gpu runtime for inference. on average 1 second inference time. 
_As of current Google Colab free provide K80 with 12G RAM with 12 Hours single run._

If you asking about training and evaluation time then @tarekeldeeb can guide you better. And if he can please take some time to release model, checkpoints and other details i.e. training/evaluation time that would be helpful.

P.S. Btw, I am just getting started with deepspeech framework and deep learning ASR.

**Comment by rachidio** [comment]
Thank you @omerasif-itu, indeed I also used an azure instance with GPU K80, I trained the model with run-quran.sh provided by @tarekeldeeb after the import of Quran data set via import-quran.sh. Unfortunately, it was running for 8 Epochs (each ~ 90 mins), but does not seem to learn anything, you can see in the following picture the steps_loss (train and test).
![Screenshot from 2020-05-29 12-06-41](https://user-images.githubusercontent.com/2559570/83362856-80361b80-a38c-11ea-985b-3665ad18651d.png)
Thanks

**Comment by omerasif-itu** [comment]
I did a smoke test: (with only one sample - train and test on single file)

`Test on data/test/train.csv - WER: 0.600000, CER: 0.222222, loss: 24.068550`

```
python -u DeepSpeech.py --noshow_progressbar \
  --alphabet_config_path files/alphabet.txt \
  --train_files data/test/train.csv \
  --test_files data/test/train.csv \
  --train_batch_size 1 \
  --test_batch_size 1 \
  --n_hidden 512 \
  --epochs 100 \
  --checkpoint_dir data/test/ckpt \
  --scorer '' \
```


**And testing with only one reciter: AL-Husary**

`Test on data/quran/quran_test.csv - WER: 0.210742, CER: 0.118998, loss: 63.033562`

**Note:** I have used `--learning_rate 0.001` as compared to default rate of `0.0001` for faster learning. and also decreases `n_hidden` units to `512`

```
python3 -u DeepSpeech.py \
  --train_files "$COMPUTE_DATA_DIR/quran_train.csv" \
  --dev_files "$COMPUTE_DATA_DIR/quran_dev.csv" \
  --test_files "$COMPUTE_DATA_DIR/quran_test.csv" \
  --alphabet_config_path "$COMPUTE_DATA_DIR/quran-alphabets.txt" \
  --scorer "$COMPUTE_DATA_DIR/lm/quran.scorer" \
  --export_dir "$COMPUTE_DATA_DIR" \
  --train_batch_size 32 \
  --dev_batch_size 32 \
  --test_batch_size 32 \
  --use_allow_growth "true" \
  --noearly_stop \
  --epochs 30 \
  --export_language "ar" \
  --n_hidden 512 \
  --dropout_rate 0.5 \
  --learning_rate 0.001 \
  --checkpoint_dir "${COMPUTE_DATA_DIR}/checkpoints" \
  --max_to_keep 2 \ 
  "$@"
```

IMO, It might take a day or two to get good training loss with at least _`100 epochs`_ and _`2048 n_hidden`_ units. 

What I can suggest is to train on 1 or 2 reciter to see results in hours and then train on all 7.

**Comment by tarekeldeeb** [comment]
@aibrahim- can you help here please and provide a checkpoint?

@omerasif-itu how did you run that test/benchmark to reach the report:
Test on data/quran/quran_test.csv - WER: 0.210742, CER: 0.118998, loss: 63.033562

Was that after training? Version 0.71? How many tests are there in your csv?

Btw, I have reach almost the same numbers before .. but when I tried a new Imam number were much lower.

**Comment by omerasif-itu** [comment]
> @omerasif-itu how did you run that test/benchmark to reach the report:
> Test on data/quran/quran_test.csv - WER: 0.210742, CER: 0.118998, loss: 63.033562
> 
> Was that after training? Version 0.71? How many tests are there in your csv?

I run this experiment with only one imam recitations (Al Husary):
**Al Husary** --> `train.csv, dev.csv, test.csv`


> python3 -u DeepSpeech.py \
>   --train_files "$COMPUTE_DATA_DIR/quran_train.csv" \
>   --dev_files "$COMPUTE_DATA_DIR/quran_dev.csv" \
>   --test_files "$COMPUTE_DATA_DIR/quran_test.csv" \
>   --alphabet_config_path "$COMPUTE_DATA_DIR/quran-alphabets.txt" \
>   --scorer "$COMPUTE_DATA_DIR/lm/quran.scorer" \
>   --export_dir "$COMPUTE_DATA_DIR" \
>   --train_batch_size 32 \
>   --dev_batch_size 32 \
>   --test_batch_size 32 \
>   --use_allow_growth "true" \
>   --noearly_stop \
>   --epochs 30 \
>   --export_language "ar" \
>   --n_hidden 512 \
>   --dropout_rate 0.5 \
>   --learning_rate 0.001 \
>   --checkpoint_dir "${COMPUTE_DATA_DIR}/checkpoints" \
>   --max_to_keep 2 \

And Just executed once (single run on Google Colab. It run for an hour. May be) with above script. 
I ran to show @rachidio  some results as he was confused about his training run and this is not a complete training report.

> Unfortunately, it was running for 8 Epochs (each ~ 90 mins), but does not seem to learn anything,

Indeed, It requires more time with this amount of hours as end to end models are data and time hungry.
 
I tested with deepspeech 0.7.1. I ran exp. in colab so can't check test files count right now. But as you write the code for splitting the data into `train/dev/test` csv's, you can apply that ratio to 6236 audio sample for single reciter. for example: for `70/20/10 `ratio: Test set could be `6236*0.10=623` audio samples.

**Comment by tarekeldeeb** [comment]
I see several problems:

1. --learning_rate 0.001 --> Should be 0.0001
2. --n_hidden 512 --> Either 1024 or 2048 (default) 

Make sure the scorer is LFS downlaoded. 8 epochs are enough to see lots of learning, loss should have reached below 40.

**Comment by omerasif-itu** [comment]
> IMO, It might take a day or two to get good training loss with at least 100 epochs and 2048 n_hidden units.
> 
> What I can suggest is to train on 1 or 2 reciter to see results in hours and then train on all 7.

I totally agree on those parameters. The only reason I changed these parameters is to show @rachidio that setup is working correctly and to see quickly that deepspeech model is learning something at least. Else your `run-quran.sh` script is totally fine.

@rachidio Are you able to resolve the training/loss issue?

**Comment by aibrahim-** [comment]
Please check my latest [model](https://github.com/tarekeldeeb/DeepSpeech-Quran/blob/master/data/quran/output_graph_imam_tusers.pb), trained with a mix between professional reciters and Tarteel amateur recitations.

Steps: 
1.Generate csv files using `bin/import_quran.py` & `bin/import_quran_tusers.py`
2. Mix the csv files generated. (Did it manually for now, could be automated) 
3. execute `run-quran.sh` script. 

Final WER:
```Test on data/quran/tusers/quran_test.csv - WER: 0.099118, CER: 0.065586, loss: 39.312599```

I only used 30 epochs as the script, but I believe there's room for improvement as the training was getting better loss results until the last epoch.

**Comment by omerasif-itu** [comment]
@aibrahim- Thank you for sharing model and results. Will definitely check it out. :+1:

**Comment by rachidio** [comment]
@omerasif-itu thank you for help, actually I realized that it need more time to reach out low loss, I will consider switching to a machine with at least two K80 to be able to run the training with full dataset and n_hidden : 2048
@aibrahim- thank you for sharing the model, I tried it with my own recitation and it is doing well. Can you please share you setup info (GPU, RAM)?

**Comment by aibrahim-** [comment]
I'm using my own machine for this, Nvidia GeForce GTX 1070 8GB and 16 GB RAM. 
Training with the data described above (using the default parameters for the scripts) takes about 14 minutes / epoch. 

I will be sharing another model tomorrow trained with more data and more epochs.

**Comment by rachidio** [comment]
Salam @tarekeldeeb

>  Make sure the scorer is LFS downlaoded. 8 epochs are enough to see lots of learning, loss should have reached below 40.

When you say to make sure the scorer 'quran.scorer' is LFS downloaded, how do you check that after everything is installed:

`apt-get update && apt-get install -y git-lfs`
`git lfs install `
`git clone https://github.com/tarekeldeeb/DeepSpeech-Quran.git`
Because, when I run this command inside DeepSpeech directory:
`git lfs ls-files`
I get only the original scorer from Mozilla team
`d0cf926ab9 - data/lm/kenlm.scorer`

**Comment by omerasif-itu** [comment]
try using `git lfs pull` to download lfs objects/files.

**Comment by rachidio** [comment]
Actually, I have the scorer but apparently it is not tracked/downloaded by git-lfs
`/DeepSpeech/data/quran/lm# ls`
`lm.binary  quran.scorer  vocab-500000.txt`

**Comment by rachidio** [comment]
@omerasif-itu does `git lfs ls-files` lists the quran scorer in your setup?

**Comment by omerasif-itu** [comment]
**Under my setup:**
```
$ git lfs ls-files
d0cf926ab9 * data/lm/kenlm.scorer
```
It seems Quran Language Model files are not being tracked under git lfs at the moment.
I am guessing it might not necessary as it is `1.7MB` in size. 

```
$ du -sh data/quran/lm/*
732K    data/quran/lm/lm.binary
1.7M    data/quran/lm/quran.scorer
388K    data/quran/lm/vocab-500000.txt

```
While `data/lm` has large scorer file.

```
$ du -sh data/lm/*
4.0K    data/lm/README.rst
8.0K    data/lm/generate_lm.py
8.0K    data/lm/generate_package.py
910M    data/lm/kenlm.scorer

```

**Comment by aibrahim-** [comment]
Yes, `data/quran/lm/*` is the one I used for training.

**Comment by aibrahim-** [comment]
For instructions on how to reproduce these files, check the [commands.txt](https://github.com/tarekeldeeb/DeepSpeech-Quran/blob/master/data/quran/commands.txt#L5)

**Comment by rachidio** [comment]
I've accomplished the training of an "imam" model with all reciters imported by the `import_quran.sh` script, it reached a score of `WER: 0.051800, CER: 0.040469, loss: 39.811401`. although it does not perform very well on new non professional data (my own recitation).
@aibrahim- I noticed that the models you shared lately, are ~48 MB while the model I generated is ~ at least x4 that with ~189MB, have you done some post compression/quantization of the trained model? how much was the `n_hidden` of your training?

**Comment by aibrahim-** [comment]
@rachidio 
I haven't done any post compression. 
I used 1024 n_hidden.

For better performance with new non-professional data, try using the `bin/import_quran_tusers.py` script with the Imam model, and then train a new model with both data.

Did you use different parameters from the ones in the `run-quran.sh`?

**Comment by rachidio** [comment]
Ok, in my case I have used `2048 n_hidden`, and all default parameters from `run-script.sh`.
I think I will try to train a new model with 1048 n_hidden as it yields great scores with less training time (min/epochs), and smaller model. thank you @aibrahim-

**Comment by omerasif-itu** [comment]
Here are my results:

**Platform**: Google Colab

**Parameters:**
```
  --train_batch_size 96 \
  --dev_batch_size 96 \
  --test_batch_size 96 \
  --use_allow_growth "true" \
  --noearly_stop \
  --epochs 30 \
  --n_hidden 1024 \
  --dropout_rate 0.5 \
  --learning_rate 0.0001 \
``` 
**Result:**
`WER: 0.056551, CER: 0.039540, loss: 24.844383`

**Comment by smalissa** [comment]
Assalam Alaikum @tarekeldeeb 
I pass through this your work and I was tried to git and see the data( records and CSV)
but I can't succeed in download it via the link that's put in the files such this  for all data files " version https://git-lfs.github.com/spec/v1
oid sha256:f0cfe426c0853af7606dce51caa05196ae0d379831ba6b7d235fb1d32a16d997
size 3789260"
I already installed  Git lfs
please, can you tell in clear  steps how I can get it 
and thank you

**Comment by omerasif-itu** [comment]
Assalam Alaikum @Modanisa-deep:
Please take a look at [this script](https://colab.research.google.com/drive/1HO57B7ZA4-vn5bm-vL1zRnmuFV99g_n4?usp=sharing) in [Google Colab](https://colab.research.google.com/) for downloading data [`bin/import_quran.sh`]. You can run it within Google Colab and then try on your local machine. For Training you can use `bin/run-quran.sh` script under `bin` directory.

**Comment by smalissa** [comment]
thank you @omerasif-itu 
oh thank you it's nice I get it
but now I see the workflow picture that's loaded  here  https://github.com/tarekeldeeb/DeepSpeech-Quran/issues/4

and  I have a question what is the meaning and the role of " filter user recordings "stage
can you explain to me in clear, please ?

**Comment by omerasif-itu** [comment]
@tarekeldeeb @aibrahim- can better guide you on that. 
What I understand from the flow is: the irrelevant (noisy, wrong, unrelated) audio files from tarteel users dataset is being filtered out so to have clean and good data for training.

Exlpore the following method in `bin/import_quran_tusers.py`

`def _eval_audio(location):{
...
}`

**Comment by omerasif-itu** [comment]
> the irrelevant (noisy, wrong, unrelated) audio files

And it is being done by looking at the difference of The Noble Quran text and transcriptions of tusers recitations.

**Comment by smalissa** [comment]
@omerasif-itu 
Oh thank you
This makes little sense
So I will ask @tarekeldeeb   for further clarification

**Comment by smalissa** [comment]
@omerasif-itu  and @tarekeldeeb 
can you provide me with the WER and CER values that you get them in the last version of your models in both  ( output_graph.pb ) and ( output_graph_imams_tusers.pb ) and also what is the specification of the server that used?

**Comment by omerasif-itu** [comment]
_Result for combined dataset ( imam recitations + tusers );_
[Imam Recitations + tusers filtered data](https://github.com/tarekeldeeb/DeepSpeech-Quran/issues/6#issuecomment-638781651)
> Final WER:
> `Test on data/quran/tusers/quran_test.csv - WER: 0.099118, CER: 0.065586, loss: 39.312599`

------------------------------------------
_Result for Imam recitations only training;_
[Imam Recitations](https://github.com/tarekeldeeb/DeepSpeech-Quran/issues/6#issuecomment-643642408)
> **Result:**
> `WER: 0.056551, CER: 0.039540, loss: 24.844383`

**_Please note that results may vary in each case due to using different hyper-parameters_.** 

> what is the specification of the server that used?

You need at least a good graphic card (GPU) for training in a rapid manner. A CPU might work but training would be extremely slow. Given you mentioned server, If you have a simple CPU based web server then you can try to train the model but It will be slow still (I have tried training on a Intel Xeon based web server and the training was pretty much slow as compared to a GPU environment) and if you have external GPU attached to it then go for it.
If you don't have a local GPU environment readily available, You can train your model using [**Google Colab**](https://colab.research.google.com/notebooks/intro.ipynb) and [**Kaggle Notebooks**](https://www.kaggle.com/docs/notebooks). In this way, you can carry out experiments quickly. Note that these platforms has limitation of usage. On Google Colab you can run code only for _12 hours._ Kaggle provide [30 Hours per week of GPU utilization](https://www.kaggle.com/docs/efficient-gpu-usage).

**Comment by omerasif-itu** [comment]
> I'm using my own machine for this, Nvidia GeForce GTX 1070 8GB and 16 GB RAM.

Here is one setup @aibrahim-  used for training. Please read this thread from beginning so you may find useful hints for your work. Regards.

**Comment by smalissa** [comment]
@omerasif-itu 
ok your GPU  memory is 16 GB?
h have my own server workstation  TITAN XP  that's supported with GPU ( 12 GB GBU memory and 1 TB SSD disk) so it's  v.good
 " Please note that results may vary in each case due to using different hyper-parameters"
can you provide me with two cases hyper-parameters, please?

**Comment by omerasif-itu** [comment]
> ok your GPU memory is 16 GB?

**Correction: This is not my setup. Please see this reply:**
(https://github.com/tarekeldeeb/DeepSpeech-Quran/issues/6#issuecomment-639159802)

> can you provide me with two cases hyper-parameters, please?

**Please take a look at:**
[case:1](https://github.com/tarekeldeeb/DeepSpeech-Quran/issues/6#issuecomment-638781651)
[case:2](https://github.com/tarekeldeeb/DeepSpeech-Quran/issues/6#issuecomment-643642408)
[Default hyper-parameters provided by tareek](https://github.com/tarekeldeeb/DeepSpeech-Quran/blob/master/bin/run-quran.sh)
[Getting started with Mozilla Deepspeech Training](https://deepspeech.readthedocs.io/en/v0.7.4/TRAINING.html)
[Deepspeech Hyper-Parameters](https://deepspeech.readthedocs.io/en/v0.7.4/TRAINING.html#fine-tuning-same-alphabet)

> Please read this thread from beginning so you may find useful hints for your work. Regards.

**Comment by smalissa** [comment]
> **Correction: This is not my setup. Please see this reply:**
> ([#6 (comment)](https://github.com/tarekeldeeb/DeepSpeech-Quran/issues/6#issuecomment-639159802))

ok I know it's for @aibrahim- 
Thank you v. much @omerasif-itu

**Comment by ghost** [comment]
> Here are my results:
> 
> **Platform**: Google Colab
> 
> **Parameters:**
> 
> ```
>   --train_batch_size 96 \
>   --dev_batch_size 96 \
>   --test_batch_size 96 \
>   --use_allow_growth "true" \
>   --noearly_stop \
>   --epochs 30 \
>   --n_hidden 1024 \
>   --dropout_rate 0.5 \
>   --learning_rate 0.0001 \
> ```
> 
> **Result:**
> `WER: 0.056551, CER: 0.039540, loss: 24.844383`

Salam,
Can you please share your Colab notebook for training? 
Thanks !

**Comment by tarekeldeeb** [comment]
I train on a local machine.

**Comment by omerasif57** [comment]
> > Here are my results:
> > **Platform**: Google Colab
> > **Parameters:**
> > ```
> >   --train_batch_size 96 \
> >   --dev_batch_size 96 \
> >   --test_batch_size 96 \
> >   --use_allow_growth "true" \
> >   --noearly_stop \
> >   --epochs 30 \
> >   --n_hidden 1024 \
> >   --dropout_rate 0.5 \
> >   --learning_rate 0.0001 \
> > ```
> > 
> > 
> > **Result:**
> > `WER: 0.056551, CER: 0.039540, loss: 24.844383`
> 
> Salam,
> Can you please share your Colab notebook for training?
> Thanks !

You can look at script mentioned here.  (Note that It is written almost 10 Months ago, so some commands/dependencies might break.) 

> Assalam Alaikum @Modanisa-deep:
> Please take a look at [this script](https://colab.research.google.com/drive/1HO57B7ZA4-vn5bm-vL1zRnmuFV99g_n4?usp=sharing) in [Google Colab](https://colab.research.google.com/) for downloading data [`bin/import_quran.sh`]. You can run it within Google Colab and then try on your local machine. For Training you can use `bin/run-quran.sh` script under `bin` directory.

**Comment by smalissa** [comment]
assalam aliakom
i want to ask about Tarteel data , when ا run the script and download the Tarteel records and got it , are these records clean and it's CSV file correct where i can use them ?
If not clean, so how i get it’s correct and clean version?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by suhad-alissa** [comment]
@***@***.***>
thanks for your reply
i understand the issue page policy and my ask is related also.
my asking is : could you please upload the Tareel data befor it filtered  which’s called “Tusers” here on the github?
with all thanks for you.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Sadmansamee** [comment]
@aibrahim- @tarekeldeeb  @omerasif57  Is this the whole step?

1. Download and install **git-lfs** from [here](https://docs.github.com/en/github/managing-large-files/installing-git-large-file-storage)
2. `git clone https://github.com/tarekeldeeb/DeepSpeech-Quran.git`
3. `git lfs pull`
4. Generate csv files using `bin/import_quran.py` & `bin/import_quran_tusers.py`
5. Mix the CSV files generated. (Did it manually, for now, could be automated)
6. Execute `bin/run-quran.sh`

**Comment by smalissa** [comment]
@aibrahim- @tarekeldeeb @omerasif57
assalam alikum
I need the checkpoint folder that was generated in Imam+tusrers model,
please can you upload it or point me to its location?
with thanks.

**Comment by tarekeldeeb** [comment]
I have updated repo with a link to:
https://drive.google.com/drive/folders/1Uzcljj1yPin9QPuNTxliOSu8haHP9Xb2?usp=sharing

Regards,

--
Tarek Eldeeb | طارق الديب <https://www.linkedin.com/in/tarekeldeeb>
Sr. SW R&D Manager | FPGA Expert

**Comment by smalissa** [comment]
thanks
but is these files are the total files?


Best  Regards,
Suhad
________________________________

**Comment by tarekeldeeb** [comment]
Yes

**Comment by smalissa** [comment]
thanks a lot


Best  Regards,
Suhad
________________________________
